### ISSUE TITLE
JS stuff (gulp file transfer from Clay's project)

### ISSUE THREAD

**Issue by kyleholliday** [claygrizzy/CollabChatApp#1]
General JS tweaking and assorted gulp business.

**Comment by ccgriswold** [comment]
Aye Sir

**Comment by ccgriswold** [comment]
Moved .js files to a js folder.  Please adjust your html src calls accordingly @kholliday88

**Comment by ccgriswold** [comment]
Yea buddy! Let's continue this thing until the next issue arises
