### ISSUE TITLE
Time Stamp function in JS

### ISSUE THREAD

**Issue by kyleholliday** [claygrizzy/CollabChatApp#5]
Let's get after it @claygrizzy

**Comment by ccgriswold** [comment]
Working on it currently.  Think I've got a lead. I'll keep you posted

**Comment by kyleholliday** [comment]
Roger that. We'll check back in at 18:30. Over and out.

**Comment by ccgriswold** [comment]
Moved to using Moment to get current time

**Comment by ccgriswold** [comment]
Completed momentintime branch and have successfully added a time stamp to each message.  As soon as it is merged I'll move on to the next upgrade.
